effects:
  one:
    type: SPEED
    time: 120
    level: 2
  two:
    type: NIGHT_VISION
    time: 120
    level: 2
  three:
    type: JUMP
    time: 120
    level: 2
  four:
    type: FAST_DIGGING
    time: 120
    level: 2

messages:
  titles:
    title: "&b&l[!] DONATION [!]"
    subtitle: "&7&o(( &f&o%target% &7&ohas just donated, you got effects! ))"
  donated:
    - " "
    - "         &f<< &3%target% &bhas &3donated &bso everyone gets effects! &f>>"
    - " &7&o(( TIP: They &f&odonated &7at our shop &b&ohttp://shop.yourstore.net&7&o! ))"
    - " "